USE DatabaseAPI;
-- Création de la table "BENEFICIARYRIGHT"

CREATE TABLE NFTRIGHT (
    NFTRIGHT_IDNFT INT NOT NULL,
    NFTRIGHT_IDRIGHT INT NOT NULL,
    PRIMARY KEY (NFTRIGHT_IDNFT, NFTRIGHT_IDRIGHT)
);
